# Generated by Django 5.2 on 2025-05-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'managed': True},
        ),
    ]
