# Generated by Django 5.1.8 on 2025-05-27 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_materiaprima_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.proveedor'),
        ),
    ]
