# Generated by Django 5.1.8 on 2025-05-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_materiaprima_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materiaprima',
            options={'managed': False},
        ),
    ]
