# Generated by Django 5.1.8 on 2025-05-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_provee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': False},
        ),
    ]
