# Generated by Django 5.1.8 on 2025-05-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_provee', '0002_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedor',
        ),
    ]
