# Generated by Django 5.2 on 2025-05-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte_provee', '0003_alter_proveedor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('idMateriaPrima', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateriaPrima', models.CharField(max_length=45)),
                ('costo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('fechaLlegada', models.DateTimeField()),
                ('fechaVencimiento', models.DateTimeField()),
            ],
            options={
                'db_table': 'materiaprima',
                'managed': False,
            },
        ),
    ]
