# Generated by Django 5.1.3 on 2024-11-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_loginusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginusuario',
            old_name='nombre',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='loginusuario',
            name='rol',
            field=models.CharField(default='Trabajador', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Trabajador', max_length=45),
        ),
    ]
