# Generated by Django 5.1.3 on 2024-11-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginusuario',
            table='login_usuario',
        ),
    ]
