# Generated by Django 3.2.12 on 2025-01-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_loginusuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiaprima_has_Usuarios',
            fields=[
                ('materiaprimaidmateriaprima', models.OneToOneField(db_column='MateriaPrimaIdMateriaPrima', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.materiaprima')),
            ],
            options={
                'db_table': 'MateriaPrima_has_Usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrimasAuditoria',
            fields=[
                ('idmateriaprima', models.OneToOneField(db_column='idMateriaPrima', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.materiaprima')),
                ('nombremateriaprimaanterior', models.CharField(blank=True, db_column='nombreMateriaPrimaAnterior', max_length=45, null=True)),
                ('costoanterior', models.IntegerField(blank=True, db_column='costoAnterior', null=True)),
                ('proveedoranterior', models.IntegerField(blank=True, db_column='proveedorAnterior', null=True)),
                ('cantidadanterior', models.IntegerField(blank=True, db_column='cantidadAnterior', null=True)),
                ('unidadmedidaanterior', models.CharField(blank=True, db_column='unidadMedidaAnterior', max_length=10, null=True)),
                ('categoriaanterior', models.CharField(blank=True, db_column='categoriaAnterior', max_length=45, null=True)),
                ('marcaanterior', models.CharField(blank=True, db_column='marcaAnterior', max_length=45, null=True)),
                ('fechallegadaanterior', models.DateTimeField(blank=True, db_column='fechaLlegadaAnterior', null=True)),
                ('fechavencimientoanterior', models.DateTimeField(blank=True, db_column='fechaVencimientoAnterior', null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, db_column='fechaModificacion', null=True)),
            ],
            options={
                'db_table': 'MateriaPrimaAuditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idprovedor', models.IntegerField(db_column='idProvedor', primary_key=True, serialize=False)),
                ('nombreprovedor', models.CharField(blank=True, db_column='nombreProvedor', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=45, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=45, null=True)),
            ],
            options={
                'db_table': 'Proveedor',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='LoginLoginusuario',
        ),
        migrations.RemoveField(
            model_name='materiaprimahasusuarios',
            name='materiaprimaidmateriaprima',
        ),
        migrations.RemoveField(
            model_name='proveedorauditoria',
            name='idproveedorauditoria',
        ),
        migrations.CreateModel(
            name='ProveedoresAuditoria',
            fields=[
                ('idproveedorauditoria', models.OneToOneField(db_column='idProveedorAuditoria', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.proveedores')),
                ('nombreanterior', models.CharField(blank=True, db_column='nombreAnterior', max_length=45, null=True)),
                ('direccionanterior', models.CharField(blank=True, db_column='direccionAnterior', max_length=45, null=True)),
                ('telefonoanterior', models.IntegerField(blank=True, db_column='telefonoAnterior', null=True)),
            ],
            options={
                'db_table': 'ProveedorAuditoria',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Materiaprimaauditoria',
        ),
        migrations.DeleteModel(
            name='MateriaprimaHasUsuarios',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Proveedorauditoria',
        ),
    ]
