# Generated by Django 5.2 on 2025-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProvedor', models.AutoField(db_column='idProvedor', primary_key=True, serialize=False)),
                ('nombreProvedor', models.CharField(db_column='nombreProvedor', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
            ],
            options={
                'db_table': 'Proveedores',
                'managed': False,
            },
        ),
    ]
