# Generated by Django 5.1.8 on 2025-05-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_prov', '0002_proveedores_delete_proveedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedores',
            options={'managed': False},
        ),
    ]
