# Generated by Django 5.1.8 on 2025-05-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_prov', '0003_alter_proveedores_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedores',
            table='Proveedores',
        ),
    ]
