# Generated by Django 5.1.8 on 2025-05-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_prov', '0004_alter_proveedores_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProvedor', models.AutoField(db_column='idProvedor', primary_key=True, serialize=False)),
                ('nombreProvedor', models.CharField(db_column='nombreProvedor', max_length=45)),
                ('direccion', models.CharField(db_column='direccion', max_length=45)),
                ('telefono', models.CharField(db_column='telefono', max_length=45)),
            ],
            options={
                'db_table': 'Proveedor',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Proveedores',
        ),
    ]
