# Generated by Django 5.1.8 on 2025-05-28 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrar_prov', '0006_auto_20250528_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'managed': True},
        ),
    ]
