# Generated by Django 5.2.3 on 2025-06-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiaprima',
            fields=[
                ('idMateriaPrima', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateriaPrima', models.CharField(max_length=45)),
                ('costo', models.IntegerField()),
                ('proveedor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('unidadMedida', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('fechaLlegada', models.DateTimeField()),
                ('fechaVencimiento', models.DateTimeField()),
            ],
            options={
                'db_table': 'MateriaPrima',
                'managed': False,
            },
        ),
    ]
