# Generated by Django 5.2 on 2025-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('idmateriaprima', models.AutoField(db_column='idMateriaPrima', primary_key=True, serialize=False)),
                ('nombreMateriaPrima', models.CharField(db_column='nombreMateriaPrima', max_length=45)),
                ('costo', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('unidadMedida', models.CharField(db_column='unidadMedida', max_length=10)),
                ('categoria', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('fechaLlegada', models.DateTimeField(db_column='fechaLlegada')),
                ('fechaVencimiento', models.DateTimeField(db_column='fechaVencimiento')),
            ],
            options={
                'db_table': 'MateriaPrima',
                'managed': False,
            },
        ),
    ]
